// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5zu3oETQ-NnjegFuS34lIcUwrFqOIPEA',
    appId: '1:1018876767083:web:61c1fcb62952f54baf3a2e',
    messagingSenderId: '1018876767083',
    projectId: 'testing-67964',
    authDomain: 'testing-67964.firebaseapp.com',
    storageBucket: 'testing-67964.firebasestorage.app',
    measurementId: 'G-SC38R5NKYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrkT6L-FkijNQrH0JlIgHiEX7f5vckLO4',
    appId: '1:1018876767083:android:0204a37eb8862770af3a2e',
    messagingSenderId: '1018876767083',
    projectId: 'testing-67964',
    storageBucket: 'testing-67964.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7OJS--pXKilw1idhHbPlDZo126QiNPI4',
    appId: '1:1018876767083:ios:6e3a827a6256f311af3a2e',
    messagingSenderId: '1018876767083',
    projectId: 'testing-67964',
    storageBucket: 'testing-67964.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7OJS--pXKilw1idhHbPlDZo126QiNPI4',
    appId: '1:1018876767083:ios:6e3a827a6256f311af3a2e',
    messagingSenderId: '1018876767083',
    projectId: 'testing-67964',
    storageBucket: 'testing-67964.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5zu3oETQ-NnjegFuS34lIcUwrFqOIPEA',
    appId: '1:1018876767083:web:58987a0c6cdde434af3a2e',
    messagingSenderId: '1018876767083',
    projectId: 'testing-67964',
    authDomain: 'testing-67964.firebaseapp.com',
    storageBucket: 'testing-67964.firebasestorage.app',
    measurementId: 'G-B3HP4W0YVL',
  );
}
